Repository bounswe/bounswe2022group1, pull requests merged in 2022-05, with the labels that each got.

#196 Kadirgokhann patch 1 Merge request
  practice-app/.gitignore
  practice-app/README.md
  practice-app/practiceapp/learningPlatform/templates/teacher_delete_course.html
  practice-app/practiceapp/learningPlatform/tests.py
  practice-app/practiceapp/learningPlatform/tests/tests_teacher_delete.py
  practice-app/practiceapp/learningPlatform/urls.py
  practice-app/practiceapp/learningPlatform/views/authentication.py
  practice-app/practiceapp/learningPlatform/views/teacher_delete_course.py
  practice-app/practiceapp/practiceapp/settings.py
Labels: Priority: Low, Status: Review Needed

#200 Login logout mustafa atay
  practice-app/practiceapp/learningPlatform/static/styles.css
  practice-app/practiceapp/learningPlatform/templates/login.html
  practice-app/practiceapp/learningPlatform/tests/test_authentication.py
  practice-app/practiceapp/learningPlatform/urls.py
  practice-app/practiceapp/learningPlatform/views/authentication.py
Labels: Priority: High, Status: Review Needed

#198 Teacher add course
  practice-app/practiceapp/learningPlatform/templates/teacher_add_course.html
  practice-app/practiceapp/learningPlatform/views/teacher_add_course.py
Labels: Priority: High, Status: Review Needed

#212 Efekan - Update on get and post
  practice-app/practiceapp/learningPlatform/views/student_give_rate.py
Labels: Priority: Critical, Status: Review Needed

#217 Teacher add course finalized with test cases.
  practice-app/practiceapp/learningPlatform/tests/test_forms.py
  practice-app/practiceapp/learningPlatform/tests/test_teacher_add_course.py
  practice-app/practiceapp/learningPlatform/urls.py
  practice-app/practiceapp/learningPlatform/views/teacher_add_course.py
Labels: Priority: High, Status: Review Needed

#216 updated for testcases
  practice-app/practiceapp/learningPlatform/tests/test_teacher_delete.py
  practice-app/practiceapp/learningPlatform/views/teacher_delete_course.py
Labels: Priority: Low, Status: Review Needed, Status: Available

#219 Unit test is written
  practice-app/practiceapp/learningPlatform/tests/test_teacher_course_statistics.py
  practice-app/practiceapp/learningPlatform/urls.py
  practice-app/practiceapp/learningPlatform/views/teacher_course_statistics.py
Labels: Type: Enhancement, Priority: High, Status: Review Needed

#222 Give Rate: Unit Tests Added
  practice-app/practiceapp/learningPlatform/tests/test_student_give_rate.py
Labels: Priority: Critical, Status: Review Needed

#243 Docker Files are added
  practice-app/Dockerfile
  practice-app/docker-compose.yml
  practice-app/practiceapp/learningPlatform/views/authentication.py
  practice-app/practiceapp/learningPlatform/views/sign_up.py
  practice-app/practiceapp/learningPlatform/views/student_my_courses.py
  practice-app/practiceapp/learningPlatform/views/student_specify_preferences.py
  practice-app/practiceapp/learningPlatform/views/teacher_add_course.py
  practice-app/practiceapp/learningPlatform/views/teacher_delete_course.py
  practice-app/practiceapp/learningPlatform/views/teacher_my_courses.py
  practice-app/practiceapp/practiceapp/settings.py
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Review Needed

#258 bug fix in authentication tests
  practice-app/practiceapp/learningPlatform/tests/test_authentication.py
Labels: Priority: Critical, Status: Review Needed

#260 Update test_teacher_delete.py for tester
  practice-app/practiceapp/learningPlatform/tests/test_teacher_delete.py
Labels: Priority: High, Status: Review Needed

#272 practice-app: The Case-Sensivity Bug
  practice-app/practiceapp/learningPlatform/views/student_give_rate.py
  practice-app/practiceapp/learningPlatform/views/student_my_courses.py
  practice-app/practiceapp/learningPlatform/views/teacher_delete_course.py
Labels: Type: Bug, Priority: Medium, Status: Completed

#273 External API error handling bug fix
  practice-app/practiceapp/learningPlatform/views/authentication.py
Labels: Priority: Critical, Status: Review Needed

#275 external_api status code is checked
  practice-app/practiceapp/learningPlatform/views/sign_up.py
Labels: Priority: Critical
